### ISSUE TITLE
Add config option to not collect IP and lat/long data in logs

### ISSUE THREAD

**Issue by tommym9** [jeylabs/laravel-audit-log#1]
Hi,

Looking at AuditLogger@log I can see that the ip address and lat/long data is collected for all log entries.

Ideally this would be able to be disabled via config. In the UK this kind of data falls foul of GDPR so we don't have any good reason to hold it in the use cases I can think of.

Cheers

Tom

**Comment by ratheeps** [comment]
Hi, @tommym9
Thank you for your feedback, we will add this features soon. 
Thanks.

**Comment by ratheeps** [comment]
Hi, @tommym9 
We have implemented your request. you can enable or disable location and IP tracking through the config using the following option.
```php
'track_location' => false,
'track_ip' => false,
```
Thanks.
